In [1]:
import sys
sys.path.insert(0, "..\scripts")

In [2]:
import transform_db
from transform_db import load_clean
import sqlite3
from sqlite3 import Error
import pandas as pd

In [3]:
load = load_clean("C:\\Users\\alexp\\src\\NBA_Models\\sqlite\\db\\nba_data.db")
basic_boxscores = load.basic_boxscores()
advanced_boxscores = load.advanced_boxscores()
scoring_boxscores = load.scoring_boxscores()
agg_boxscores = load.boxscores()
players = load.players()

In [4]:
pd.set_option('display.max_columns', None)

### Basic Boxscores

In [5]:
display(basic_boxscores.head())

,SEASON,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,PLUS_MINUS
0,2013-14,1610612748,MIA,Miami Heat,0021300002,2013-10-29,MIA vs. CHI,W,240,37,72,0.514,11,20,0.550,22,29,0.759,5,35,40,26,10,7,20,21,107,12
1,2013-14,1610612741,CHI,Chicago Bulls,0021300002,2013-10-29,CHI @ MIA,L,240,35,83,0.422,7,26,0.269,18,23,0.783,11,30,41,23,11,4,19,27,95,-12
2,2013-14,1610612746,LAC,Los Angeles Clippers,0021300003,2013-10-29,LAC @ LAL,L,240,41,83,0.494,8,21,0.381,13,23,0.565,10,30,40,27,11,4,16,21,103,-13
3,2013-14,1610612747,LAL,Los Angeles Lakers,0021300003,2013-10-29,LAL vs. LAC,W,240,42,93,0.452,14,29,0.483,18,28,0.643,18,34,52,23,8,6,19,23,116,13
4,2013-14,1610612753,ORL,Orlando Magic,0021300001,2013-10-29,ORL @ IND,L,240,36,93,0.387,9,19,0.474,6,10,0.600,13,26,39,17,10,6,19,26,87,-10

### Advanced Boxscores

In [6]:
display(advanced_boxscores.head())

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,E_OFF_RATING,OFF_RATING,E_DEF_RATING,DEF_RATING,E_NET_RATING,NET_RATING,AST_PCT,AST_TOV,AST_RATIO,OREB_PCT,DREB_PCT,REB_PCT,E_TM_TOV_PCT,TM_TOV_PCT,EFG_PCT,TS_PCT,USG_PCT,E_USG_PCT,E_PACE,PACE,PACE_PER40,POSS,PIE
0,0021300001,1610612753,Magic,ORL,Orlando,240.000000:00,84.1,92.6,101.0,103.2,-16.8,-10.6,0.472,0.89,12.7,0.383,0.683,0.505,18.375,20.2,0.435,0.447,1.0,0.194,99.74,94.0,78.33,94,0.339
1,0021300001,1610612754,Pacers,IND,Indiana,240.000000:00,101.0,103.2,84.1,92.6,16.8,10.6,0.500,0.81,13.8,0.317,0.617,0.495,21.857,22.3,0.528,0.570,1.0,0.198,99.74,94.0,78.33,94,0.661
2,0021300002,1610612748,Heat,MIA,Miami,240.000000:00,107.3,108.1,93.9,96.9,13.3,11.1,0.703,1.30,19.9,NaN,0.706,NaN,20.048,20.2,0.590,0.631,1.0,0.197,100.44,98.5,82.08,99,0.599
3,0021300002,1610612741,Bulls,CHI,Chicago,240.000000:00,93.9,96.9,107.3,108.1,-13.3,-11.1,0.657,1.21,17.0,0.294,NaN,NaN,18.790,19.4,0.464,0.510,1.0,0.198,100.44,98.5,82.08,98,0.401
4,0021300003,1610612747,Lakers,LAL,Los Angeles,240.000000:00,109.1,117.2,103.9,105.1,5.2,12.1,0.548,1.21,15.6,0.439,0.745,0.577,17.871,19.2,0.527,0.551,1.0,0.195,102.72,98.5,82.08,99,0.503

### Scoring Boxscores

In [7]:
display(scoring_boxscores.head())

,GAME_ID,TEAM_ID,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CITY,MIN,PCT_FGA_2PT,PCT_FGA_3PT,PCT_PTS_2PT,PCT_PTS_2PT_MR,PCT_PTS_3PT,PCT_PTS_FB,PCT_PTS_FT,PCT_PTS_OFF_TOV,PCT_PTS_PAINT,PCT_AST_2PM,PCT_UAST_2PM,PCT_AST_3PM,PCT_UAST_3PM,PCT_AST_FGM,PCT_UAST_FGM
0,0021300001,1610612753,Magic,ORL,Orlando,240.000000:00,0.796,0.204,0.621,0.230,0.310,0.115,0.069,0.241,0.391,0.370,0.630,0.778,0.222,0.472,0.528
1,0021300001,1610612754,Pacers,IND,Indiana,240.000000:00,0.761,0.239,0.557,0.186,0.216,0.134,0.227,0.299,0.371,0.444,0.556,0.714,0.286,0.500,0.500
2,0021300002,1610612748,Heat,MIA,Miami,240.000000:00,0.722,0.278,0.486,0.168,0.308,0.093,0.206,0.140,0.318,0.577,0.423,1.000,0.000,0.703,0.297
3,0021300002,1610612741,Bulls,CHI,Chicago,240.000000:00,0.687,0.313,0.589,0.063,0.221,0.179,0.189,0.316,0.526,0.571,0.429,1.000,0.000,0.657,0.343
4,0021300003,1610612747,Lakers,LAL,Los Angeles,240.000000:00,0.688,0.312,0.483,0.121,0.362,0.112,0.155,0.241,0.362,0.429,0.571,0.786,0.214,0.548,0.452

### Aggregated Boxscores

In [8]:
display(agg_boxscores.head())

,GAME_ID,TEAM_ID_team,TEAM_ID_opp,SEASON_team,GAME_DATE_team,TEAM_NAME_team,TEAM_NAME_opp,MATCHUP_team,TEAM_ABBREVIATION_team,HOME_GAME_team,TEAM_SCORE_team,POINT_DIFF_team,WL_team,RECORD_team,FG2M_team,FG2A_team,FG3M_team,FG3A_team,FTM_team,FTA_team,OREB_team,DREB_team,REB_team,AST_team,STL_team,BLK_team,TOV_team,PF_team,PTS_team,PLUS_MINUS_team,E_OFF_RATING_team,OFF_RATING_team,E_DEF_RATING_team,DEF_RATING_team,E_NET_RATING_team,NET_RATING_team,POSS_team,PIE_team,PTS_2PT_MR_team,PTS_FB_team,PTS_OFF_TOV_team,PTS_PAINT_team,AST_2PM_team,AST_3PM_team,UAST_2PM_team,UAST_3PM_team,TEAM_ABBREVIATION_opp,HOME_GAME_opp,TEAM_SCORE_opp,POINT_DIFF_opp,WL_opp,RECORD_opp,FG2M_opp,FG2A_opp,FG3M_opp,FG3A_opp,FTM_opp,FTA_opp,OREB_opp,DREB_opp,REB_opp,AST_opp,STL_opp,BLK_opp,TOV_opp,PF_opp,PTS_opp,PLUS_MINUS_opp,E_OFF_RATING_opp,OFF_RATING_opp,E_DEF_RATING_opp,DEF_RATING_opp,E_NET_RATING_opp,NET_RATING_opp,POSS_opp,PIE_opp,PTS_2PT_MR_opp,PTS_FB_opp,PTS_OFF_TOV_opp,PTS_PAINT_opp,AST_2PM_opp,AST_3PM_opp,UAST_2PM_opp,UAST_3PM_opp
0,0021300003,1610612747,1610612746,2013-14,2013-10-29 00:00:00,Los Angeles Lakers,Los Angeles Clippers,LAL vs. LAC,LAL,1,116,13,1,1,28,64,14,29,18,28,18,34,52,23,8,6,19,23,116,13,109.1,117.2,103.9,105.1,5.2,12.1,99.0,0.503,14,12,27,41,12,11,15,2,LAC,0,103,-13,0,0,33,62,8,21,13,23,10,30,40,27,11,4,16,21,103,-13,103.9,105.1,109.1,117.2,-5.2,-12.1,98.0,0.497,18,18,25,47,19,7,13,1
1,0021300001,1610612754,1610612753,2013-14,2013-10-29 00:00:00,Indiana Pacers,Orlando Magic,IND vs. ORL,IND,1,97,10,1,1,27,54,7,17,22,32,10,34,44,17,4,18,21,13,97,10,101.0,103.2,84.1,92.6,16.8,10.6,94.0,0.661,18,12,29,35,11,4,15,2,ORL,0,87,-10,0,0,27,74,9,19,6,10,13,26,39,17,10,6,19,26,87,-10,84.1,92.6,101.0,103.2,-16.8,-10.6,94.0,0.339,20,10,20,34,9,7,17,1
2,0021300004,1610612739,1610612751,2013-14,2013-10-30 00:00:00,Cleveland Cavaliers,Brooklyn Nets,CLE vs. BKN,CLE,1,98,4,1,1,30,69,5,15,23,34,16,32,48,21,7,3,14,20,98,4,101.1,105.4,95.4,101.1,5.7,4.3,93.0,0.525,25,10,18,34,17,4,12,1,BKN,0,94,-4,0,0,24,58,9,24,19,24,9,28,37,24,8,8,15,27,94,-4,95.4,101.1,101.1,105.4,-5.7,-4.3,93.0,0.475,17,12,15,29,15,9,9,0
3,0021300017,1610612744,1610612747,2013-14,2013-10-30 00:00:00,Golden State Warriors,Los Angeles Lakers,GSW vs. LAL,GSW,1,125,31,1,1,31,59,15,27,18,23,7,41,48,34,8,9,15,22,125,31,120.1,119.0,88.5,90.4,31.6,28.7,105.0,0.703,22,22,22,40,23,10,7,4,LAL,0,94,-31,0,0,27,71,8,18,16,21,9,30,39,19,5,4,17,22,94,-31,88.5,90.4,120.1,119.0,-31.6,-28.7,104.0,0.297,14,17,12,40,11,7,15,1
4,0021300010,1610612750,1610612753,2013-14,2013-10-30 00:00:00,Minnesota Timberwolves,Orlando Magic,MIN vs. ORL,MIN,1,120,5,1,1,34,75,8,25,28,34,14,35,49,27,7,3,15,19,120,5,103.5,107.1,102.8,101.8,0.7,5.4,112.0,0.536,21,18,18,45,19,8,14,0,ORL,0,115,-5,0,0,37,73,10,27,11,18,14,40,54,21,7,6,18,29,115,-5,102.8,101.8,103.5,107.1,-0.7,-5.4,113.0,0.464,27,11,14,46,13,7,23,3

### Player Game Stats

In [9]:
display(players.head())

,SEASON_YEAR,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,TOV,STL,BLK,BLKA,PF,PFD,PTS,PLUS_MINUS,NBA_FANTASY_PTS,DD2,TD3,GP_RANK,W_RANK,L_RANK,W_PCT_RANK,MIN_RANK,FGM_RANK,FGA_RANK,FG_PCT_RANK,FG3M_RANK,FG3A_RANK,FG3_PCT_RANK,FTM_RANK,FTA_RANK,FT_PCT_RANK,OREB_RANK,DREB_RANK,REB_RANK,AST_RANK,TOV_RANK,STL_RANK,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS,WNBA_FANTASY_PTS_RANK,AVAILABLE_FLAG
0,2013-14,203104,Marquis Teague,Marquis,1610612751,BKN,Brooklyn Nets,0021301224,2014-04-16T00:00:00,BKN @ CLE,L,41.483333,2,9,0.222,1,3,0.333,2,2,1.0,0,5,5,4,4,1,0,3,1,1,7,-19,18.0,0,0,1,12875,12875,12875,718,14748,9044,20418,5024,6256,6480,6578,8189,1,13390,4234,7025,3686,848,4715,7678,25052,4560,12544,13794,24664,13000,2167,47,19.0,11395,1.0
1,2013-14,1713,Vince Carter,Vince,1610612742,DAL,Dallas Mavericks,0021301216,2014-04-16T00:00:00,DAL @ MEM,L,26.403333,4,11,0.364,1,4,0.250,0,2,0.0,0,2,2,0,2,2,0,0,4,4,9,7,15.4,0,0,1,12875,12875,12875,10949,8580,6386,15813,5024,4189,8282,13990,8189,13990,13390,12561,15412,17694,4624,1559,7678,1,21355,2985,11331,5756,14787,2167,47,16.0,13525,1.0
2,2013-14,202705,MarShon Brooks,MarShon,1610612747,LAL,Los Angeles Lakers,0021301221,2014-04-16T00:00:00,LAL @ SAS,W,8.750000,3,4,0.750,0,1,0.000,1,2,0.5,0,1,1,0,1,0,0,0,1,1,7,2,7.2,0,0,1,1,1,1,22284,11446,17592,1759,10050,11917,10050,10700,8189,10714,13390,16983,19088,17694,9505,11946,7678,1,4560,12544,13794,9778,20416,2167,47,8.0,19315,1.0
3,2013-14,203507,Giannis Antetokounmpo,Giannis,1610612749,MIL,Milwaukee Bucks,0021301217,2014-04-16T00:00:00,MIL vs. ATL,L,26.250000,4,6,0.667,2,3,0.667,0,0,0.0,1,4,5,3,1,0,1,0,5,2,10,4,22.5,0,0,1,12875,12875,12875,11082,8580,13930,2791,2352,6256,1761,13990,14885,13990,6679,6220,7025,5378,9505,11946,2516,1,24081,8067,10132,7995,10058,2167,47,22.0,9405,1.0
4,2013-14,2223,Samuel Dalembert,Samuel,1610612742,DAL,Dallas Mavericks,0021301216,2014-04-16T00:00:00,DAL @ MEM,L,11.466667,1,2,0.500,0,0,0.000,0,0,0.0,1,2,3,0,2,0,0,0,5,0,2,-5,3.6,0,0,1,12875,12875,12875,21203,18183,21008,7679,10050,15492,10050,13990,14885,13990,6679,12561,12106,17694,4624,11946,7678,1,24081,18504,20191,17192,22671,2167,47,5.0,21464,1.0

# Model

In [10]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Masking

WARNING:tensorflow:From c:\Users\alexp\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.