In [1]:
import sys
sys.path.insert(0, "..\scripts")

# Team Basic Boxscores

In [2]:
import sqlite3
from sqlite3 import Error
import pandas as pd

def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
    except Error as e:
        print(e)

    return conn

conn = create_connection("C:\\Users\\alexp\\src\\NBA_Models\\sqlite\\db\\nba_data.db")
cur = conn.cursor()
cur.execute("SELECT * FROM team_basic_boxscores")
rows = cur.fetchall()

db_list = []

for row in rows:
    db_list.append(row)


basic_boxscores_db = pd.DataFrame(data=db_list)

basic_boxscores_db.columns = ['SEASON TEXT', 'TEAM_ID INTEGER', 'TEAM_ABBREVIATION TEXT', 
            'TEAM_NAME TEXT', 'GAME_ID TEXT', 'GAME_DATE DATE', 'MATCHUP TEXT', 'WL TEXT', 'MIN INTEGER', 'FGM INTEGER', 'FGA INTEGER', 
            'FG_PCT FLOAT', 'FG3M INTEGER', 'FG3A  INTEGER', 'FG3_PCT FLOAT', 'FTM INTEGER', 'FTA INTEGER', 'FT_PCT FLOAT', 'OREB INTEGER',
            'DREB INTEGER', 'REB INTEGER', 'AST INTEGER', 'STL INTEGER', 'BLK INTEGER', 'TOV INTEGER', 'PF INTEGER', 'PTS INTEGER', 
            'PLUS_MINUS INTEGER']

display(basic_boxscores_db)

,SEASON TEXT,TEAM_ID INTEGER,TEAM_ABBREVIATION TEXT,TEAM_NAME TEXT,GAME_ID TEXT,GAME_DATE DATE,MATCHUP TEXT,WL TEXT,MIN INTEGER,FGM INTEGER,...,OREB INTEGER,DREB INTEGER,REB INTEGER,AST INTEGER,STL INTEGER,BLK INTEGER,TOV INTEGER,PF INTEGER,PTS INTEGER,PLUS_MINUS INTEGER
0,2013-14,1610612748,MIA,Miami Heat,0021300002,2013-10-29,MIA vs. CHI,W,240,37,...,5,35,40,26,10,7,20,21,107,12
1,2013-14,1610612741,CHI,Chicago Bulls,0021300002,2013-10-29,CHI @ MIA,L,240,35,...,11,30,41,23,11,4,19,27,95,-12
2,2013-14,1610612746,LAC,Los Angeles Clippers,0021300003,2013-10-29,LAC @ LAL,L,240,41,...,10,30,40,27,11,4,16,21,103,-13
3,2013-14,1610612747,LAL,Los Angeles Lakers,0021300003,2013-10-29,LAL vs. LAC,W,240,42,...,18,34,52,23,8,6,19,23,116,13
4,2013-14,1610612753,ORL,Orlando Magic,0021300001,2013-10-29,ORL @ IND,L,240,36,...,13,26,39,17,10,6,19,26,87,-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26489,2023-24,1610612738,BOS,Boston Celtics,0022300389,2023-12-23,BOS @ LAC,W,240,49,...,15,36,51,33,4,5,10,19,145,37
26490,2023-24,1610612746,LAC,LA Clippers,0022300389,2023-12-23,LAC vs. BOS,L,240,41,...,9,25,34,25,4,4,11,24,108,-37
26491,2023-24,1610612752,NYK,New York Knicks,0022300388,2023-12-23,NYK vs. MIL,L,240,41,...,11,30,41,17,5,2,11,22,111,-19
26492,2023-24,1610612749,MIL,Milwaukee Bucks,0022300388,2023-12-23,MIL @ NYK,W,240,48,...,12,41,53,25,4,2,14,22,130,19
26493,2023-24,1610612758,SAC,Sacramento Kings,0022300400,2023-12-23,SAC vs. MIN,L,240,37,...,8,32,40,23,10,2,11,20,98,-12

# Team Advanced Boxscores

In [3]:
cur2 = conn.cursor()
cur2.execute("SELECT * FROM team_advanced_boxscores")
rows2 = cur2.fetchall()

db_advanced_list = []

for row in rows2:
    db_advanced_list.append(row)

advanced_boxscores_db = pd.DataFrame(data=db_advanced_list)

advanced_boxscores_db.columns = ['GAME_ID TEXT', 'TEAM_ID INTEGER', 'TEAM_NAME TEXT', 
            'TEAM_ABBREVIATION TEXT', 'TEAM_CITY TEXT', 'MIN TEXT', 'E_OFF_RATING FLOAT', 'OFF_RATING FLOAT', 'E_DEF_RATING FLOAT', 
            'DEF_RATING FLOAT', 'E_NET_RATING FLOAT', 'NET_RATING FLOAT', 'AST_PCT FLOAT', 'AST_TOV FLOAT', 
            'AST_RATIO FLOAT', 'OREB_PCT FLOAT', 'DREB_PCT FLOAT', 'REB_PCT FLOAT', 'E_TM_TOV_PCT FLOAT', 
            'TM_TOV_PCT FLOAT', 'EFG_PCT FLOAT', 'TS_PCT FLOAT', 'USG_PCT FLOAT', 'E_USG_PCT FLOAT', 'E_PACE FLOAT', 
            'PACE FLOAT', 'PACE_PER40 FLOAT', 'POSS FLOAT', 'PIE FLOAT']

display(advanced_boxscores_db.loc[:26463])

,GAME_ID TEXT,TEAM_ID INTEGER,TEAM_NAME TEXT,TEAM_ABBREVIATION TEXT,TEAM_CITY TEXT,MIN TEXT,E_OFF_RATING FLOAT,OFF_RATING FLOAT,E_DEF_RATING FLOAT,DEF_RATING FLOAT,...,TM_TOV_PCT FLOAT,EFG_PCT FLOAT,TS_PCT FLOAT,USG_PCT FLOAT,E_USG_PCT FLOAT,E_PACE FLOAT,PACE FLOAT,PACE_PER40 FLOAT,POSS FLOAT,PIE FLOAT
0,0021300003,1610612747,Lakers,LAL,Los Angeles,240.000000:00,109.1,117.2,103.9,105.1,...,19.2,0.527,0.551,1.0,0.195,102.72,98.5,82.08,99.0,0.503
1,0021300003,1610612746,Clippers,LAC,Los Angeles,240.000000:00,103.9,105.1,109.1,117.2,...,16.3,0.542,0.553,1.0,0.200,102.72,98.5,82.08,98.0,0.497
2,0021300001,1610612753,Magic,ORL,Orlando,240.000000:00,84.1,92.6,101.0,103.2,...,20.2,0.435,0.447,1.0,0.194,99.74,94.0,78.33,94.0,0.339
3,0021300001,1610612754,Pacers,IND,Indiana,240.000000:00,101.0,103.2,84.1,92.6,...,22.3,0.528,0.570,1.0,0.198,99.74,94.0,78.33,94.0,0.661
4,0021300002,1610612748,Heat,MIA,Miami,240.000000:00,107.3,108.1,93.9,96.9,...,20.2,0.590,0.631,1.0,0.197,100.44,98.5,82.08,99.0,0.599
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26459,0022300389,1610612738,Celtics,BOS,Boston,240.000000:00,143.1,146.5,110.7,111.3,...,10.1,0.654,0.682,1.0,0.196,99.46,98.0,81.67,99.0,0.634
26460,0022300398,1610612759,Spurs,SAS,San Antonio,None,NaN,0.0,NaN,0.0,...,NaN,NaN,NaN,1.0,0.000,NaN,NaN,NaN,0.0,NaN
26461,0022300398,1610612742,Mavericks,DAL,Dallas,None,NaN,0.0,NaN,0.0,...,NaN,NaN,NaN,1.0,0.000,NaN,NaN,NaN,0.0,NaN
26462,0022300396,1610612739,Cavaliers,CLE,Cleveland,None,NaN,0.0,NaN,0.0,...,NaN,NaN,NaN,1.0,0.000,NaN,NaN,NaN,0.0,NaN
26463,0022300396,1610612741,Bulls,CHI,Chicago,None,NaN,0.0,NaN,0.0,...,NaN,NaN,NaN,1.0,0.000,NaN,NaN,NaN,0.0,NaN

# Team Scoring Boxscores

In [4]:
cur.execute("SELECT * FROM team_scoring_boxscores")
rows3 = cur.fetchall()

db_scoring_list = []

for row in rows3:
    db_scoring_list.append(row)

scoring_boxscores_db = pd.DataFrame(data=db_scoring_list)

scoring_boxscores_db.columns = ['GAME_ID TEXT', 'TEAM_ID INTEGER', 'TEAM_NAME TEXT', 'TEAM_ABBREVIATION TEXT', 'TEAM_CITY TEXT',
       'MIN TEXT', 'PCT_FGA_2PT FLOAT', 'PCT_FGA_3PT FLOAT', 'PCT_PTS_2PT FLOAT', 'PCT_PTS_2PT_MR FLOAT',
       'PCT_PTS_3PT FLOAT', 'PCT_PTS_FB FLOAT', 'PCT_PTS_FT FLOAT', 'PCT_PTS_OFF_TOV FLOAT',
       'PCT_PTS_PAINT FLOAT', 'PCT_AST_2PM FLOAT', 'PCT_UAST_2PM FLOAT', 'PCT_AST_3PM FLOAT',
       'PCT_UAST_3PM FLOAT', 'PCT_AST_FGM FLOAT', 'PCT_UAST_FGM FLOAT']

display(scoring_boxscores_db)

,GAME_ID TEXT,TEAM_ID INTEGER,TEAM_NAME TEXT,TEAM_ABBREVIATION TEXT,TEAM_CITY TEXT,MIN TEXT,PCT_FGA_2PT FLOAT,PCT_FGA_3PT FLOAT,PCT_PTS_2PT FLOAT,PCT_PTS_2PT_MR FLOAT,...,PCT_PTS_FB FLOAT,PCT_PTS_FT FLOAT,PCT_PTS_OFF_TOV FLOAT,PCT_PTS_PAINT FLOAT,PCT_AST_2PM FLOAT,PCT_UAST_2PM FLOAT,PCT_AST_3PM FLOAT,PCT_UAST_3PM FLOAT,PCT_AST_FGM FLOAT,PCT_UAST_FGM FLOAT
0,0021300001,1610612753,Magic,ORL,Orlando,240.000000:00,0.796,0.204,0.621,0.230,...,0.115,0.069,0.241,0.391,0.370,0.630,0.778,0.222,0.472,0.528
1,0021300001,1610612754,Pacers,IND,Indiana,240.000000:00,0.761,0.239,0.557,0.186,...,0.134,0.227,0.299,0.371,0.444,0.556,0.714,0.286,0.500,0.500
2,0021300002,1610612748,Heat,MIA,Miami,240.000000:00,0.722,0.278,0.486,0.168,...,0.093,0.206,0.140,0.318,0.577,0.423,1.000,0.000,0.703,0.297
3,0021300002,1610612741,Bulls,CHI,Chicago,240.000000:00,0.687,0.313,0.589,0.063,...,0.179,0.189,0.316,0.526,0.571,0.429,1.000,0.000,0.657,0.343
4,0021300003,1610612747,Lakers,LAL,Los Angeles,240.000000:00,0.688,0.312,0.483,0.121,...,0.112,0.155,0.241,0.362,0.429,0.571,0.786,0.214,0.548,0.452
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26481,0022300385,1610612742,Mavericks,DAL,Dallas,240.000000:00,0.604,0.396,0.583,0.063,...,0.271,0.198,0.208,0.521,0.393,0.607,1.000,0.000,0.514,0.486
26482,0022300387,1610612758,Kings,SAC,Sacramento,240.000000:00,0.542,0.458,0.533,0.067,...,0.175,0.167,0.175,0.467,0.656,0.344,0.917,0.083,0.727,0.273
26483,0022300387,1610612756,Suns,PHX,Phoenix,240.000000:00,0.716,0.284,0.648,0.076,...,0.105,0.210,0.143,0.571,0.412,0.588,1.000,0.000,0.487,0.513
26484,0022300386,1610612764,Wizards,WAS,Washington,240.000000:00,0.639,0.361,0.559,0.051,...,0.195,0.161,0.161,0.508,0.515,0.485,0.727,0.273,0.568,0.432
26485,0022300386,1610612744,Warriors,GSW,Golden State,240.000000:00,0.536,0.464,0.450,0.062,...,0.140,0.132,0.039,0.388,0.690,0.310,0.722,0.278,0.702,0.298

In [5]:
import transform_db
from transform_db import transform

obj = transform(conn=conn,start_season=2013,end_season=2023)
df = obj.load_team_data()
df2 = obj.create_matchups(df)
display(df2)

,SEASON_team,TEAM_ID_team,TEAM_ABBREVIATION_team,TEAM_NAME_team,GAME_ID,GAME_DATE_team,MATCHUP_team,WL_team,MIN_team,FGM_team,...,PCT_PTS_FB_opp,PCT_PTS_FT_opp,PCT_PTS_OFF_TOV_opp,PCT_PTS_PAINT_opp,PCT_AST_2PM_opp,PCT_UAST_2PM_opp,PCT_AST_3PM_opp,PCT_UAST_3PM_opp,PCT_AST_FGM_opp,PCT_UAST_FGM_opp
1,2013-14,1610612748,MIA,Miami Heat,0021300002,2013-10-29,MIA vs. CHI,W,240,37,...,0.179,0.189,0.316,0.526,0.571,0.429,1.000,0.000,0.657,0.343
2,2013-14,1610612741,CHI,Chicago Bulls,0021300002,2013-10-29,CHI @ MIA,L,240,35,...,0.093,0.206,0.140,0.318,0.577,0.423,1.000,0.000,0.703,0.297
5,2013-14,1610612746,LAC,Los Angeles Clippers,0021300003,2013-10-29,LAC @ LAL,L,240,41,...,0.112,0.155,0.241,0.362,0.429,0.571,0.786,0.214,0.548,0.452
6,2013-14,1610612747,LAL,Los Angeles Lakers,0021300003,2013-10-29,LAL vs. LAC,W,240,42,...,0.184,0.126,0.243,0.466,0.606,0.394,0.875,0.125,0.659,0.341
9,2013-14,1610612753,ORL,Orlando Magic,0021300001,2013-10-29,ORL @ IND,L,240,36,...,0.134,0.227,0.299,0.371,0.444,0.556,0.714,0.286,0.500,0.500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52978,2023-24,1610612766,CHA,Charlotte Hornets,0022300390,2023-12-23,CHA vs. DEN,L,240,34,...,0.118,0.118,0.225,0.471,0.556,0.444,0.833,0.167,0.641,0.359
52981,2023-24,1610612738,BOS,Boston Celtics,0022300389,2023-12-23,BOS @ LAC,W,240,49,...,0.120,0.139,0.037,0.463,0.533,0.467,0.818,0.182,0.610,0.390
52982,2023-24,1610612746,LAC,LA Clippers,0022300389,2023-12-23,LAC vs. BOS,L,240,41,...,0.145,0.152,0.090,0.317,0.583,0.417,0.760,0.240,0.673,0.327
52985,2023-24,1610612752,NYK,New York Knicks,0022300388,2023-12-23,NYK vs. MIL,L,240,41,...,0.169,0.138,0.077,0.354,0.344,0.656,0.875,0.125,0.521,0.479
52986,2023-24,1610612749,MIL,Milwaukee Bucks,0022300388,2023-12-23,MIL @ NYK,W,240,48,...,0.099,0.180,0.144,0.432,0.344,0.656,0.667,0.333,0.415,0.585